name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "* * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRlCS_TOKEN }}
          output_action: none

          # Options
          user: rhysdh540
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_gists: no
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_people: no
          plugin_projects: no
          plugin_stars: no

      - run: |
        set +e
        git checkout metrics-renders
        git config user.name rhysdh540
        git config user.email 98863820+rhysdh540@users.noreply.github.com
        sudo mv /metrics_renders/* ./
        git add --all
        git commit -m "metrics update"
        git push
          
